# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{sankey}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jan Stępień"]
  s.date = %q{2010-02-18}
  s.description = %q{A small tool which generates Sankey diagrams.}
  s.email = %q{jstepien@users.sourceforge.net}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "examples/coffee.rb",
     "lib/generator.rb",
     "lib/imagedata.rb",
     "lib/point.rb",
     "lib/process.rb",
     "lib/processvertex.rb",
     "lib/reagent.rb",
     "lib/renderers/renderer.rb",
     "lib/renderers/rvg.rb",
     "lib/sankey.rb",
     "lib/vertex.rb",
     "sankey.gemspec"
  ]
  s.homepage = %q{http://github.com/jstepien/sankey}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Sankey diagrams generator}
  s.test_files = [
    "examples/coffee.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rmagick>, [">= 0"])
    else
      s.add_dependency(%q<rmagick>, [">= 0"])
    end
  else
    s.add_dependency(%q<rmagick>, [">= 0"])
  end
end

